name: "edotor"

services:
  edotor:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        - VERSION=v2.3.1
    image: edotor:2.3.1
    environment:
      - NETWORK_ACCESS=internal
      - VIRTUAL_HOST=gv.sums01.hex.tno.nl
      - VIRTUAL_PORT=5173
      - HTTPS_METHOD=nohttps
    restart: always
    networks:
      - revprox

networks:
  revprox:
    name: revprox
    external: true
